//
//  JSONStubs.swift
//  GenesisTestTask
//
//  Created by Alexey Savchenko on 7/5/18.
//  Copyright © 2018 Alexey Savchenko. All rights reserved.
//

import Foundation

class JSONStubs {
	static let searchResponse =
	"""
	{
	    "total_count": 18856,
	    "incomplete_results": false,
	    "items": [
	        {
	            "id": 76954504,
	            "node_id": "MDEwOlJlcG9zaXRvcnk3Njk1NDUwNA==",
	            "name": "react-tetris",
	            "full_name": "chvin/react-tetris",
	            "owner": {
	                "login": "chvin",
	                "id": 5383506,
	                "node_id": "MDQ6VXNlcjUzODM1MDY=",
	                "avatar_url": "https://avatars2.githubusercontent.com/u/5383506?v=4",
	                "gravatar_id": "",
	                "url": "https://api.github.com/users/chvin",
	                "html_url": "https://github.com/chvin",
	                "followers_url": "https://api.github.com/users/chvin/followers",
	                "following_url": "https://api.github.com/users/chvin/following{/other_user}",
	                "gists_url": "https://api.github.com/users/chvin/gists{/gist_id}",
	                "starred_url": "https://api.github.com/users/chvin/starred{/owner}{/repo}",
	                "subscriptions_url": "https://api.github.com/users/chvin/subscriptions",
	                "organizations_url": "https://api.github.com/users/chvin/orgs",
	                "repos_url": "https://api.github.com/users/chvin/repos",
	                "events_url": "https://api.github.com/users/chvin/events{/privacy}",
	                "received_events_url": "https://api.github.com/users/chvin/received_events",
	                "type": "User",
	                "site_admin": false
	            },
	            "private": false,
	            "html_url": "https://github.com/chvin/react-tetris",
	            "description": "Use React, Redux, Immutable to code Tetris. 🎮",
	            "fork": false,
	            "url": "https://api.github.com/repos/chvin/react-tetris",
	            "forks_url": "https://api.github.com/repos/chvin/react-tetris/forks",
	            "keys_url": "https://api.github.com/repos/chvin/react-tetris/keys{/key_id}",
	            "collaborators_url": "https://api.github.com/repos/chvin/react-tetris/collaborators{/collaborator}",
	            "teams_url": "https://api.github.com/repos/chvin/react-tetris/teams",
	            "hooks_url": "https://api.github.com/repos/chvin/react-tetris/hooks",
	            "issue_events_url": "https://api.github.com/repos/chvin/react-tetris/issues/events{/number}",
	            "events_url": "https://api.github.com/repos/chvin/react-tetris/events",
	            "assignees_url": "https://api.github.com/repos/chvin/react-tetris/assignees{/user}",
	            "branches_url": "https://api.github.com/repos/chvin/react-tetris/branches{/branch}",
	            "tags_url": "https://api.github.com/repos/chvin/react-tetris/tags",
	            "blobs_url": "https://api.github.com/repos/chvin/react-tetris/git/blobs{/sha}",
	            "git_tags_url": "https://api.github.com/repos/chvin/react-tetris/git/tags{/sha}",
	            "git_refs_url": "https://api.github.com/repos/chvin/react-tetris/git/refs{/sha}",
	            "trees_url": "https://api.github.com/repos/chvin/react-tetris/git/trees{/sha}",
	            "statuses_url": "https://api.github.com/repos/chvin/react-tetris/statuses/{sha}",
	            "languages_url": "https://api.github.com/repos/chvin/react-tetris/languages",
	            "stargazers_url": "https://api.github.com/repos/chvin/react-tetris/stargazers",
	            "contributors_url": "https://api.github.com/repos/chvin/react-tetris/contributors",
	            "subscribers_url": "https://api.github.com/repos/chvin/react-tetris/subscribers",
	            "subscription_url": "https://api.github.com/repos/chvin/react-tetris/subscription",
	            "commits_url": "https://api.github.com/repos/chvin/react-tetris/commits{/sha}",
	            "git_commits_url": "https://api.github.com/repos/chvin/react-tetris/git/commits{/sha}",
	            "comments_url": "https://api.github.com/repos/chvin/react-tetris/comments{/number}",
	            "issue_comment_url": "https://api.github.com/repos/chvin/react-tetris/issues/comments{/number}",
	            "contents_url": "https://api.github.com/repos/chvin/react-tetris/contents/{+path}",
	            "compare_url": "https://api.github.com/repos/chvin/react-tetris/compare/{base}...{head}",
	            "merges_url": "https://api.github.com/repos/chvin/react-tetris/merges",
	            "archive_url": "https://api.github.com/repos/chvin/react-tetris/{archive_format}{/ref}",
	            "downloads_url": "https://api.github.com/repos/chvin/react-tetris/downloads",
	            "issues_url": "https://api.github.com/repos/chvin/react-tetris/issues{/number}",
	            "pulls_url": "https://api.github.com/repos/chvin/react-tetris/pulls{/number}",
	            "milestones_url": "https://api.github.com/repos/chvin/react-tetris/milestones{/number}",
	            "notifications_url": "https://api.github.com/repos/chvin/react-tetris/notifications{?since,all,participating}",
	            "labels_url": "https://api.github.com/repos/chvin/react-tetris/labels{/name}",
	            "releases_url": "https://api.github.com/repos/chvin/react-tetris/releases{/id}",
	            "deployments_url": "https://api.github.com/repos/chvin/react-tetris/deployments",
	            "created_at": "2016-12-20T12:26:11Z",
	            "updated_at": "2018-07-05T07:47:17Z",
	            "pushed_at": "2018-04-02T12:11:25Z",
	            "git_url": "git://github.com/chvin/react-tetris.git",
	            "ssh_url": "git@github.com:chvin/react-tetris.git",
	            "clone_url": "https://github.com/chvin/react-tetris.git",
	            "svn_url": "https://github.com/chvin/react-tetris",
	            "homepage": "https://chvin.github.io/react-tetris/?lan=en",
	            "size": 3338,
	            "stargazers_count": 3453,
	            "watchers_count": 3453,
	            "language": "JavaScript",
	            "has_issues": true,
	            "has_projects": true,
	            "has_downloads": true,
	            "has_wiki": true,
	            "has_pages": true,
	            "forks_count": 586,
	            "mirror_url": null,
	            "archived": false,
	            "open_issues_count": 0,
	            "license": null,
	            "forks": 586,
	            "open_issues": 0,
	            "watchers": 3453,
	            "default_branch": "master",
	            "score": 136.91252
	        },
	        {
	            "id": 94079558,
	            "node_id": "MDEwOlJlcG9zaXRvcnk5NDA3OTU1OA==",
	            "name": "vue-tetris",
	            "full_name": "Binaryify/vue-tetris",
	            "owner": {
	                "login": "Binaryify",
	                "id": 12221718,
	                "node_id": "MDQ6VXNlcjEyMjIxNzE4",
	                "avatar_url": "https://avatars1.githubusercontent.com/u/12221718?v=4",
	                "gravatar_id": "",
	                "url": "https://api.github.com/users/Binaryify",
	                "html_url": "https://github.com/Binaryify",
	                "followers_url": "https://api.github.com/users/Binaryify/followers",
	                "following_url": "https://api.github.com/users/Binaryify/following{/other_user}",
	                "gists_url": "https://api.github.com/users/Binaryify/gists{/gist_id}",
	                "starred_url": "https://api.github.com/users/Binaryify/starred{/owner}{/repo}",
	                "subscriptions_url": "https://api.github.com/users/Binaryify/subscriptions",
	                "organizations_url": "https://api.github.com/users/Binaryify/orgs",
	                "repos_url": "https://api.github.com/users/Binaryify/repos",
	                "events_url": "https://api.github.com/users/Binaryify/events{/privacy}",
	                "received_events_url": "https://api.github.com/users/Binaryify/received_events",
	                "type": "User",
	                "site_admin": false
	            },
	            "private": false,
	            "html_url": "https://github.com/Binaryify/vue-tetris",
	            "description": "Use Vue, Vuex, Immutable to code Tetris.使用 Vue, Vuex, Immutable 做俄罗斯方块 ",
	            "fork": false,
	            "url": "https://api.github.com/repos/Binaryify/vue-tetris",
	            "forks_url": "https://api.github.com/repos/Binaryify/vue-tetris/forks",
	            "keys_url": "https://api.github.com/repos/Binaryify/vue-tetris/keys{/key_id}",
	            "collaborators_url": "https://api.github.com/repos/Binaryify/vue-tetris/collaborators{/collaborator}",
	            "teams_url": "https://api.github.com/repos/Binaryify/vue-tetris/teams",
	            "hooks_url": "https://api.github.com/repos/Binaryify/vue-tetris/hooks",
	            "issue_events_url": "https://api.github.com/repos/Binaryify/vue-tetris/issues/events{/number}",
	            "events_url": "https://api.github.com/repos/Binaryify/vue-tetris/events",
	            "assignees_url": "https://api.github.com/repos/Binaryify/vue-tetris/assignees{/user}",
	            "branches_url": "https://api.github.com/repos/Binaryify/vue-tetris/branches{/branch}",
	            "tags_url": "https://api.github.com/repos/Binaryify/vue-tetris/tags",
	            "blobs_url": "https://api.github.com/repos/Binaryify/vue-tetris/git/blobs{/sha}",
	            "git_tags_url": "https://api.github.com/repos/Binaryify/vue-tetris/git/tags{/sha}",
	            "git_refs_url": "https://api.github.com/repos/Binaryify/vue-tetris/git/refs{/sha}",
	            "trees_url": "https://api.github.com/repos/Binaryify/vue-tetris/git/trees{/sha}",
	            "statuses_url": "https://api.github.com/repos/Binaryify/vue-tetris/statuses/{sha}",
	            "languages_url": "https://api.github.com/repos/Binaryify/vue-tetris/languages",
	            "stargazers_url": "https://api.github.com/repos/Binaryify/vue-tetris/stargazers",
	            "contributors_url": "https://api.github.com/repos/Binaryify/vue-tetris/contributors",
	            "subscribers_url": "https://api.github.com/repos/Binaryify/vue-tetris/subscribers",
	            "subscription_url": "https://api.github.com/repos/Binaryify/vue-tetris/subscription",
	            "commits_url": "https://api.github.com/repos/Binaryify/vue-tetris/commits{/sha}",
	            "git_commits_url": "https://api.github.com/repos/Binaryify/vue-tetris/git/commits{/sha}",
	            "comments_url": "https://api.github.com/repos/Binaryify/vue-tetris/comments{/number}",
	            "issue_comment_url": "https://api.github.com/repos/Binaryify/vue-tetris/issues/comments{/number}",
	            "contents_url": "https://api.github.com/repos/Binaryify/vue-tetris/contents/{+path}",
	            "compare_url": "https://api.github.com/repos/Binaryify/vue-tetris/compare/{base}...{head}",
	            "merges_url": "https://api.github.com/repos/Binaryify/vue-tetris/merges",
	            "archive_url": "https://api.github.com/repos/Binaryify/vue-tetris/{archive_format}{/ref}",
	            "downloads_url": "https://api.github.com/repos/Binaryify/vue-tetris/downloads",
	            "issues_url": "https://api.github.com/repos/Binaryify/vue-tetris/issues{/number}",
	            "pulls_url": "https://api.github.com/repos/Binaryify/vue-tetris/pulls{/number}",
	            "milestones_url": "https://api.github.com/repos/Binaryify/vue-tetris/milestones{/number}",
	            "notifications_url": "https://api.github.com/repos/Binaryify/vue-tetris/notifications{?since,all,participating}",
	            "labels_url": "https://api.github.com/repos/Binaryify/vue-tetris/labels{/name}",
	            "releases_url": "https://api.github.com/repos/Binaryify/vue-tetris/releases{/id}",
	            "deployments_url": "https://api.github.com/repos/Binaryify/vue-tetris/deployments",
	            "created_at": "2017-06-12T09:37:34Z",
	            "updated_at": "2018-07-05T16:53:58Z",
	            "pushed_at": "2017-10-03T05:05:55Z",
	            "git_url": "git://github.com/Binaryify/vue-tetris.git",
	            "ssh_url": "git@github.com:Binaryify/vue-tetris.git",
	            "clone_url": "https://github.com/Binaryify/vue-tetris.git",
	            "svn_url": "https://github.com/Binaryify/vue-tetris",
	            "homepage": "http://binaryify.github.io/vue-tetris/",
	            "size": 1228,
	            "stargazers_count": 1512,
	            "watchers_count": 1512,
	            "language": "JavaScript",
	            "has_issues": true,
	            "has_projects": true,
	            "has_downloads": true,
	            "has_wiki": false,
	            "has_pages": false,
	            "forks_count": 229,
	            "mirror_url": null,
	            "archived": false,
	            "open_issues_count": 3,
	            "license": {
	                "key": "mit",
	                "name": "MIT License",
	                "spdx_id": "MIT",
	                "url": "https://api.github.com/licenses/mit",
	                "node_id": "MDc6TGljZW5zZTEz"
	            },
	            "forks": 229,
	            "open_issues": 3,
	            "watchers": 1512,
	            "default_branch": "master",
	            "score": 96.606346
	        }
	    ]
	}
	"""
}
